$_=shift;
tr/ /_/;
die "$_? Ära ropenda!\n" if /[^\w()]/;
exit 1 unless open(F, '-|') or exec "/usr/bin/host", "-t", "txt", "$_.wp.dg.cx";
$_ = join(' ', <F>);
close F;
die "Mu pea pole prügikast\n" unless s/^.*descriptive text "//s and s/"$//;
s/" "//gs;
s/\\(.)/\1/gs;
print $_;
